### ISSUE TITLE
[BUG] Infinite saving window

### ISSUE THREAD

**Issue by DaringDuch69** [solvedDev/bridge.#81] opened 2019-09-30 16:13 UTC
Bug: After creating a new item and adding the format version and attempting to save it, it begins to start, to my knowledge an endless saving screen.

1. Click New File
2. Name & Select A Template
3. Add Format Version (I Used 1.12.0)
4. Add minecraft: item, description, components, etc.
5. Click Save.

Platform: Windows 10
Bridge Version: 0.13.8

**Comment by solvedDev** [comment] 2019-09-30 16:35
Thanks for the report! Sounds like a serious issue, gonna get on it right now and keep you updated!

**Comment by DaringDuch69** [comment] 2019-09-30 16:48
Thank you.

**Comment by solvedDev** [comment] 2019-09-30 17:14
@DaringDuch69 Could you please provide me with a screenshot of what exactly you wrote (for your item)?

**Comment by solvedDev** [comment] 2019-09-30 17:59
@DaringDuch69 I am unable to reproduce this issue. Could you please follow these steps and report back?

1. Open the settings menu (FILE > PREFERENCES > SETTINGS)
2. Choose the "Developer Mode" tab (gear icon)
3. Click on the orange button. A console should appear to the right of the window
4. Switch to the tab called "console"
5. Try to create a RP and send me a screenshot of the contents of the console

This information can help me trying to understand why saving doesn't work for you.

**Comment by BlkCatGmg** [comment] 2019-09-30 18:34
> @DaringDuch69 I am unable to reproduce this issue. Could you please follow these steps and report back?
> 
> 1. Open the settings menu (FILE > PREFERENCES > SETTINGS)
> 2. Choose the "Developer Mode" tab (gear icon)
> 3. Click on the orange button. A console should appear to the right of the window
> 4. Switch to the tab called "console"
> 5. Save an item and send me a screenshot of the contents of the console
> 
> This information can help me trying to understand why saving doesn't work for you.

If gives the error:
Error: bridge.core
Error: ENOENT: No such file or directory open "<Path to save>"

**Comment by DaringDuch69** [comment] 2019-09-30 18:48
[image: image.png]

**Comment by solvedDev** [comment] 2019-09-30 19:03
Thanks for the reports! This issue will be fixed inside the next version :)

**Comment by DaringDuch69** [comment] 2019-09-30 19:03
How do I fix that issue?

**Closed** 2019-09-30 19:02 UTC
Labels: Bug

**Comment by solvedDev** [comment] 2019-09-30 19:14
This will be fixed with the next release of bridge. You can also fix it by clicking on the explorer icon on the far right of the sidebar toolbar and creating the following folders inside the file explorer:
1) "entities"
2) "animations" with subfolder "bridge" ("animations/bridge"
