### ISSUE TITLE
[BUG]Does not show textures in the file blocks.json

### ISSUE THREAD

**Issue by EndiKM** [solvedDev/bridge.#78] opened 2019-09-25 15:19 UTC
After adding the first texture I was able to add a second texture up and down but this texture was on a different block so I added another one that is not on the block and does not display this texture in the blocks.json file but after creating the block that contained this texture I was able to add this texture up and down but I don't want to create a block that is not in the game to add texture up and down.
![no on creative and give](https://user-images.githubusercontent.com/54553687/65614713-64d26f80-dfb8-11e9-9bab-cc0224eef269.PNG)
![terrain_textures](https://user-images.githubusercontent.com/54553687/65616044-a82ddd80-dfba-11e9-83b3-82f51567c08a.PNG)
![blocks and textures log on my wood](https://user-images.githubusercontent.com/54553687/65614753-74ea4f00-dfb8-11e9-8aa7-00ba3711f19e.PNG)
![new wood](https://user-images.githubusercontent.com/54553687/65614760-787dd600-dfb8-11e9-9237-26193eb958a8.PNG)

**Comment by solvedDev** [comment] 2019-09-25 16:57
Hey @EndiKM, I am having a hard time understanding the bug you're experiencing. Could you please provide me with some reproduction steps so I can see and experience the issue myself? Could you also talk a bit about what exactly the problem is? Is it an auto-completion problem?

**Comment by EndiKM** [comment] 2019-09-25 18:40
The point is that one texture is supplemented on the sides and if I want to complement the top and bottom with a different texture, I can only choose a texture that is already on another block.

**Comment by EndiKM** [comment] 2019-09-25 18:43
I can't choose a texture that isn't on any block, i.e. one that I just put into the blocks folder.

And if you want, I can make a movie where I can show you everything :)

**Comment by solvedDev** [comment] 2019-09-29 14:17
@EndiKM, a video would probably be helpful. I really don't understand what the issue is you're having.

You are aware though that every texture you want to use has to be declared inside the terrain_texture.json file, right? There's no 1 to 1 mapping from block to terrain_texture. A block can have multiple terrain_textures assigned to it.

**Comment by EndiKM** [comment] 2019-09-29 17:32
In terrain_textures.json, I assigned two textures to the block and it looks like this

{
	"red_maple_wood": {
		"textures": [
			"textures/blocks/red_maple_wood.png",
			"textures/blocks/log"
		]
	}
}

but when I want to choose a texture called "log" in the blocks.json file, this texture does not display, only those textures that already have their block are displayed

**Comment by solvedDev** [comment] 2019-09-29 20:17
That's not how these files work and therefor not a bug. You use these arrays to have different textures per data value of a block (see: wool). Please check the vanilla files as a reference.

**Closed by solvedDev** 2019-09-29 20:17 UTC
Labels: Bug
