### ISSUE TITLE
[BUG] Javascript error, no suck file or directory settings.

### ISSUE THREAD

**Issue by kouichi12** [solvedDev/bridge.#128] opened 2019-12-18 18:48 UTC
Hello, finally downloaded your 32-bit compatible bridge!
But I got a problem.

Here's the pic.
It seems it doesn't detect or create it's own setting that's needed to run when it's first installing.
am I missing some dependency require to download?

Sorry bad english

Thank you.

![Screenshot_30](https://user-images.githubusercontent.com/58889736/71114080-f80ef000-2209-11ea-9263-e72de5d27e4d.png)

**Comment by solvedDev** [comment] 2019-12-18 19:39
Duplicate of #126; fixed for the next release :)

**Closed by solvedDev** 2019-12-18 19:39 UTC
Labels: Bug, Duplicate
