### ISSUE TITLE
[Feature] Choosing an Identifier when starting a project

### ISSUE THREAD

**Issue by RandomYT2802** [solvedDev/bridge.#73] opened 2019-09-18 13:03 UTC
When you start a project, you should be able to choose the identifier that is used before you type an item. For example, I choose the identifier as, "RandomAddon"

i type "RandomItem", and it shows up in the editor as "RandomAddon:RandomItem". This does not apply unless you override it, for example, "NotRandomAddon:RandomItem". I don't know why anyone would override it, but it's there just in case.

I actually suggested this before, but I worded it horribly, and it didn't get added the way I thought. You don't need to change it, but now the issue is worse than before, because you have to override "bridge:RandomItem" everytime I make an item (this is only because I sometimes forget to type an identifier).

**Comment by solvedDev** [comment] 2019-09-18 13:38
That's a duplicate of #61 :) The feature you proposed wasn't worked on yet, the newly added suggestions with the "bridge:" prefix were done before your proposal

**Closed by solvedDev** 2019-09-18 13:38 UTC
Labels: Duplicate, Feature

**Comment by solvedDev** [comment] 2019-09-18 17:45
Feature completed today, scheduled for the next version
